### ISSUE TITLE
aosp repo sync 失败问题

### ISSUE THREAD

**Issue by jolly336** [tuna/issues#1228]
使用 wget 下载了 aosp-latest.tar 初始化包，解压后进行 `repo sync` 时出错了，这是啥问题？

```
▶ repo sync                      
Traceback (most recent call last):
  File "/Volumes/Samsung_T5/android_source/aosp/.repo/repo/main.py", line 630, in <module>
    _Main(sys.argv[1:])
  File "/Volumes/Samsung_T5/android_source/aosp/.repo/repo/main.py", line 604, in _Main
    result = run()
  File "/Volumes/Samsung_T5/android_source/aosp/.repo/repo/main.py", line 597, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/Volumes/Samsung_T5/android_source/aosp/.repo/repo/main.py", line 261, in _Run
    result = cmd.Execute(copts, cargs)
  File "/Volumes/Samsung_T5/android_source/aosp/.repo/repo/subcmds/sync.py", line 831, in Execute
    self._UpdateManifestProject(opt, mp, manifest_name)
  File "/Volumes/Samsung_T5/android_source/aosp/.repo/repo/subcmds/sync.py", line 749, in _UpdateManifestProject
    if mp.HasChanges:
  File "/Volumes/Samsung_T5/android_source/aosp/.repo/repo/project.py", line 3275, in HasChanges
    elif self._revlist(not_rev(HEAD), revid):
  File "/Volumes/Samsung_T5/android_source/aosp/.repo/repo/project.py", line 2806, in _revlist
    return self.work_git.rev_list(*a, **kw)
  File "/Volumes/Samsung_T5/android_source/aosp/.repo/repo/project.py", line 3019, in rev_list
    raise GitError('%s rev-list %s: %s' %
error.GitError: manifests rev-list ('^HEAD', '22ab5f31aa401a7db6357483c63a8a0aad7de704', '--'): fatal: bad revision '^HEAD'
```

**Comment by Harry-Chen** [comment]
我无法复现这一问题，请务必使用 Linux 环境进行开发
