### ISSUE TITLE
repo sync 报错

### ISSUE THREAD

**Issue by lxn348567248** [tuna/issues#1252]
报错信息
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 172, in accepter
    c = self.listener.accept()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 453, in accept
    c = self._listener.accept()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 593, in accept
    s, self._last_accepted = self._socket.accept()
  File "/usr/lib/python3.6/socket.py", line 210, in accept
    sock = socket(self.family, type, self.proto, fileno=fd)
  File "/usr/lib/python3.6/socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
SystemError: <method-wrapper '__init__' of socket object at 0x6fffff3f3b88> returned NULL without setting an error

 这个是下载aosp 源码时，到repo sync 报的

工具是 cygwin

**Comment by skyzh** [comment]
cygwin 的 repo sync 可以从官方源同步吗？

目测不是镜像站的问题，建议向 cygwin 项目反馈。

**Comment by shankerwangmiao** [comment]
从报错信息上来看，似乎是您的 Python 运行环境出现了问题。建议您排查 Python 是否能正常工作。
