### ISSUE TITLE
anaconda 使用tuna作为default channel 同时使用v2ray，conda install存在故障

### ISSUE THREAD

**Issue by Sam-zcl** [tuna/issues#1253]
问题描述：
- 我按照https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/ 所述，修改了anaconda所使用的的镜像源。但是在同时挂上梯子之后，conda install 的命令会报错。

报错：
`(base) PS C:\Users\xxx> conda install spyder
Collecting package metadata (current_repodata.json): failed

--------------------------------- ERROR REPORT------------------------------------------------

    Traceback (most recent call last):
      File "E:\Anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "E:\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "E:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "E:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "E:\Anaconda3\lib\site-packages\conda\cli\install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "E:\Anaconda3\lib\site-packages\conda\core\solve.py", line 114, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "E:\Anaconda3\lib\site-packages\conda\core\solve.py", line 157, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "E:\Anaconda3\lib\site-packages\conda\core\solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "E:\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "E:\Anaconda3\lib\site-packages\conda\core\solve.py", line 425, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "E:\Anaconda3\lib\site-packages\conda\core\solve.py", line 1020, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "E:\Anaconda3\lib\site-packages\conda\core\index.py", line 288, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "E:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 140, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "E:\Anaconda3\lib\concurrent\futures\_base.py", line 611, in result_iterator
        yield fs.pop().result()
      File "E:\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
        return self.__get_result()
      File "E:\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
        raise self._exception
      File "E:\Anaconda3\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "E:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 132, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "E:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 145, in query
        self.load()
      File "E:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 209, in load
        _internal_state = self._load()
      File "E:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 371, in _load
        raw_repodata_str = fetch_repodata_remote_request(
      File "E:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 694, in fetch_repodata_remote_request
        resp = session.get(join_url(url, filename), headers=headers, proxies=session.proxies,
      File "E:\Anaconda3\lib\site-packages\requests\sessions.py", line 555, in get
        return self.request('GET', url, **kwargs)
      File "E:\Anaconda3\lib\site-packages\requests\sessions.py", line 542, in request
        resp = self.send(prep, **send_kwargs)
      File "E:\Anaconda3\lib\site-packages\requests\sessions.py", line 655, in send
        r = adapter.send(request, **kwargs)
      File "E:\Anaconda3\lib\site-packages\requests\adapters.py", line 439, in send
        resp = conn.urlopen(
      File "E:\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
        self._prepare_proxy(conn)
      File "E:\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
        conn.connect()
      File "E:\Anaconda3\lib\site-packages\urllib3\connection.py", line 359, in connect
        conn = self._connect_tls_proxy(hostname, conn)
      File "E:\Anaconda3\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
        return ssl_wrap_socket(
      File "E:\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
        ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
      File "E:\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
        return ssl_context.wrap_socket(sock)
      File "E:\Anaconda3\lib\ssl.py", line 500, in wrap_socket
        return self.sslsocket_class._create(
      File "E:\Anaconda3\lib\ssl.py", line 997, in _create
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname

$ E:\Anaconda3\Scripts\conda-script.py install spyder
`
可能出现的问题：
- v2ray改变了系统代理，tuna的镜像不能通过代理使用？

期待的解决方案：
- 使用v2ray的同时，conda也可以连接上tuna的镜像源

**Comment by skyzh** [comment]
看起来不像是镜像站应该处理的问题，建议到 anaconda repository 反馈。

在我的机器上是可以配置代理并使用 conda 的。参考 https://stackoverflow.com/questions/66642705/why-requests-raise-this-exception-check-hostname-requires-server-hostname ，可能是代理服务器配置有问题。是否方便提供系统中代理相关的环境变量的值？

**Comment by shankerwangmiao** [comment]
TUNA 不限制使用代理连接镜像站。该问题应该是 Anaconda 打包的 urlib 的 bug 所致。参考 https://github.com/urllib3/urllib3/issues/2075

**Comment by milozen** [comment]
conda install urllib3==1.25.11
降低 urllib3 的版本能解决该问题
