### ISSUE TITLE
Jenkins镜像源无法使用

### ISSUE THREAD

**Issue by CoderSHH** [tuna/issues#1302]
#### 发生了什么（What happened）
Jenkins镜像源无法使用。包括Ubuntu的镜像源，Jenkins中插件的镜像源等。

#### 期望的现象（What you expected to happen）
正常获取镜像源

#### 如何重现（How to reproduce it）
1. 参考[jenkins官方教程](https://pkg.jenkins.io/debian-stable/)安装jenkins。
2. 官方解析自动跳转清华镜像源(mirrors.tuna.tsinghua.edu.cn)
3. 镜像源无法建立连接
```bash
udo apt-get install jenkins=2.249.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  daemon
The following NEW packages will be installed:
  daemon jenkins
0 upgraded, 2 newly installed, 0 to remove and 3 not upgraded.
Need to get 66.8 MB/66.9 MB of archives.
After this operation, 67.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Err:1 https://pkg.jenkins.io/debian-stable binary/ jenkins 2.249.2                                                                                                                  
  Cannot initiate the connection to mirrors.tuna.tsinghua.edu.cn:443 (2402:f000:1:408:8100::1). - connect (101: Network is unreachable) Could not connect to mirrors.tuna.tsinghua.edu.cn:443 (101.6.8.193). - connect (111: Connection refused)
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/jenkins/debian-stable/jenkins_2.249.2_all.deb  Cannot initiate the connection to mirrors.tuna.tsinghua.edu.cn:443 (2402:f000:1:408:8100::1). - connect (101: Network is unreachable) Could not connect to mirrors.tuna.tsinghua.edu.cn:443 (101.6.8.193). - connect (111: Connection refused)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

现象二：
1. 在安装完成的Jenkins中下载plugin
2. 解析地址后自动跳转清华源
3. 插件下载错误
```bash
java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1383)
Caused: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1561)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1391)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1291)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2739)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2651)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1830)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3061)
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
	at java.net.URLConnection.getContentLength(URLConnection.java:485)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:412)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1266)
Caused: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1282)
Caused: java.io.IOException: Failed to load https://updates.jenkins.io/download/plugins/workflow-step-api/2.24/workflow-step-api.hpi to /var/lib/jenkins/plugins/workflow-step-api.jpi.tmp
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1289)
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/workflow-step-api/2.24/workflow-step-api.hpi (redirected to: https://mirrors.tuna.tsinghua.edu.cn/jenkins/plugins/workflow-step-api/2.24/workflow-step-api.hpi)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1323)
	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1871)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2164)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1845)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:121)
	at java.lang.Thread.run(Thread.java:748)
```

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：Ubuntu 20.0.4 LTS
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
您好，

从错误中看，似乎是您的计算机无法正常连接镜像站，请确认访问 https://mirrors.tuna.tsinghua.edu.cn 是否正常。

**Comment by CoderSHH** [comment]
感谢你的回复：
我下午（14时到17时）尝试时的情况有：
1. 可以访问 https://mirrors.tuna.tsinghua.edu.cn ，并正常打开镜像中文件，但响应速度非常缓慢。平均每个页面几分钟的响应时间
2. ping  https://mirrors.tuna.tsinghua.edu.cn ，出现大量超时以及丢包现象
3. 在jenkins中下载资源时超时。由于超时时间设置较短，导致无法正常获取资源文件

目前的情况（晚上19时）：
1. 能正常访问 https://mirrors.tuna.tsinghua.edu.cn ，打开速度正常
2.  https://mirrors.tuna.tsinghua.edu.cn 无丢包现象

初步怀疑是这几天的台风、暴雨等恶劣天气导致部分通信线路中断，从而导致下午我访问清华资源站速度下降到几乎为0。目前已恢复正常
