### ISSUE TITLE
北外Fedora镜像出现HTTP 403错误

### ISSUE THREAD

**Issue by maidmeow4** [tuna/issues#1314]
#### 发生了什么（What happened）
`sudo dnf update` 时，出现403报错，但是我手动单独更新报错的那几个包时，又可以更新，
此后再执行 `sudo dnf update` 又会报错，周而复始 :recycle: 
#### 期望的现象（What you expected to happen）
`sudo dnf update` 应该毫无违和感的运行下去
#### 如何重现（How to reproduce it）
不确定，报错看起来是随机出现的
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：Fedora workstation 33
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：ISP: 中国联通

----
<details>
  <summary>当时DNF部分输出</summary>

```
事务概要
====================================================================================
安装   10 软件包
升级  310 软件包
移除    1 软件包

总下载：574 M
确定吗？[y/N]： Y
下载软件包：
(1/320): python3-packaging-20.4-2.fc33.noarch.rpm   180 kB/s |  67 kB     00:00    
(2/320): libsodium-1.0.18-6.fc33.x86_64.rpm         413 kB/s | 166 kB     00:00    
[MIRROR] python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm: Status code: 403 for https://mirrors.bfsu.edu.cn/fedora/releases/33/Everything/x86_64/os/Packages/p/python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm (IP: 2001:da8:20f:4435:4adf:37ff:fe55:2840)
(3/320): python3-pyparsing-2.4.7-4.fc33.noarch.rpm  338 kB/s | 149 kB     00:00    
[MIRROR] kernel-devel-5.13.9-100.fc33.x86_64.rpm: Status code: 403 for https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/Packages/k/kernel-devel-5.13.9-100.fc33.x86_64.rpm (IP: 2001:da8:20f:4435:4adf:37ff:fe55:2840)
[MIRROR] python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm: Status code: 403 for https://mirrors.bfsu.edu.cn/fedora/releases/33/Everything/x86_64/os/Packages/p/python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm (IP: 2001:da8:20f:4435:4adf:37ff:fe55:2840)
[MIRROR] kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm: Status code: 403 for https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/Packages/k/kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm (IP: 2001:da8:20f:4435:4adf:37ff:fe55:2840)
[MIRROR] kernel-devel-5.13.9-100.fc33.x86_64.rpm: Status code: 403 for https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/Packages/k/kernel-devel-5.13.9-100.fc33.x86_64.rpm (IP: 2001:da8:20f:4435:4adf:37ff:fe55:2840)
[MIRROR] python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm: Status code: 403 for https://mirrors.bfsu.edu.cn/fedora/releases/33/Everything/x86_64/os/Packages/p/python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm (IP: 2001:da8:20f:4435:4adf:37ff:fe55:2840)
[MIRROR] kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm: Status code: 403 for https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/Packages/k/kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm (IP: 2001:da8:20f:4435:4adf:37ff:fe55:2840)
[FAILED] kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
(5-6/320): python3-sim  0% [                      ] 685 kB/s | 2.4 MB     14:13 ETA
下载的软件包保存在缓存中，直到下次成功执行事务。
您可以通过执行 'dnf clean packages' 删除软件包缓存。
错误：下载软件包出错 :
  Cannot download Packages/k/kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm: All mirrors were tried
```

</details>

**Comment by shankerwangmiao** [comment]
请您用 curl 请求上面任意文件，并提供输出。

**Comment by shankerwangmiao** [comment]
经核对日志发现，dnf 在请求上述包的时候，有的请求带了正确的 UA，有的请求没有 UA。后者触发了相关的屏蔽规则，因此返回了 403。

<details>
<summary>对应日志</summary>

```
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:25 +0800] "GET /fedora/updates/33/Modular/x86_64/repodata/c5478ca6745292346b9ae10b8fc9f2d2751c5da145822de26c5661859e815b8e-modules.yaml.gz HTTP/2.0" 200 47203 "application/octet-stream" "-" "libdnf (Fedora 33; matecompiz; Linux.x86_64)" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:26 +0800] "GET /fedora/updates/33/Modular/x86_64/repodata/3797d82bfb0477e35efcdc25967fc8642b3a83c5578816ae896066c36d2e1e17-primary.xml.zck HTTP/2.0" 206 808718 "application/octet-stream" "-" "libdnf (Fedora 33; matecompiz; Linux.x86_64)" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:26 +0800] "GET /fedora/updates/33/Modular/x86_64/repodata/b26297b7af24add073dfc87c613c6fb0f01e974b4523bdb2db9e8a582a025004-updateinfo.xml.zck HTTP/2.0" 206 116 "application/octet-stream" "-" "-" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:26 +0800] "GET /fedora/updates/33/Modular/x86_64/repodata/9137dd8a35a911f3533722cb9d4c01c3ac920392078302395401fc7d8a3e4331-filelists.xml.zck HTTP/2.0" 206 2716159 "application/octet-stream" "-" "-" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:26 +0800] "GET /fedora/updates/33/Modular/x86_64/repodata/b26297b7af24add073dfc87c613c6fb0f01e974b4523bdb2db9e8a582a025004-updateinfo.xml.zck HTTP/2.0" 206 3226 "application/octet-stream" "-" "-" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:44 +0800] "GET /fedora/releases/33/Everything/x86_64/os/Packages/p/python3-packaging-20.4-2.fc33.noarch.rpm HTTP/2.0" 200 68417 "application/x-redhat-package-manager" "-" "libdnf (Fedora 33; matecompiz; Linux.x86_64)" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:44 +0800] "GET /fedora/releases/33/Everything/x86_64/os/Packages/l/libsodium-1.0.18-6.fc33.x86_64.rpm HTTP/2.0" 200 170047 "application/x-redhat-package-manager" "-" "libdnf (Fedora 33; matecompiz; Linux.x86_64)" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:44 +0800] "GET /fedora/releases/33/Everything/x86_64/os/Packages/p/python3-pyparsing-2.4.7-4.fc33.noarch.rpm HTTP/2.0" 200 153068 "application/x-redhat-package-manager" "-" "libdnf (Fedora 33; matecompiz; Linux.x86_64)" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:44 +0800] "GET /fedora/releases/33/Everything/x86_64/os/Packages/p/python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm HTTP/2.0" 403 2436 "text/html; charset=utf-8" "-" "-" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:44 +0800] "GET /fedora/updates/33/Everything/x86_64/Packages/k/kernel-devel-5.13.9-100.fc33.x86_64.rpm HTTP/2.0" 403 2436 "text/html; charset=utf-8" "-" "-" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:44 +0800] "GET /fedora/releases/33/Everything/x86_64/os/Packages/p/python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm HTTP/2.0" 403 2436 "text/html; charset=utf-8" "-" "-" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:44 +0800] "GET /fedora/updates/33/Everything/x86_64/Packages/k/kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm HTTP/2.0" 403 2436 "text/html; charset=utf-8" "-" "-" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:44 +0800] "GET /fedora/updates/33/Everything/x86_64/Packages/k/kernel-devel-5.13.9-100.fc33.x86_64.rpm HTTP/2.0" 403 2436 "text/html; charset=utf-8" "-" "-" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:44 +0800] "GET /fedora/releases/33/Everything/x86_64/os/Packages/p/python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm HTTP/2.0" 403 2436 "text/html; charset=utf-8" "-" "-" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:44 +0800] "GET /fedora/updates/33/Everything/x86_64/Packages/k/kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm HTTP/2.0" 403 2436 "text/html; charset=utf-8" "-" "-" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:44 +0800] "GET /fedora/updates/33/Everything/x86_64/Packages/k/kernel-devel-5.13.9-100.fc33.x86_64.rpm HTTP/2.0" 403 2436 "text/html; charset=utf-8" "-" "-" "-" https
2408:832e:a0a1:<redacted> - - [17/Aug/2021:11:48:44 +0800] "GET /fedora/releases/33/Everything/x86_64/os/Packages/p/python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm HTTP/2.0" 403 2436 "text/html; charset=utf-8" "-" "-" "-" https
```
</details>

**Comment by skyzh** [comment]
恐怕又是 zchunk 的 bug？可以去 https://github.com/zchunk/zchunk 提一下（

**Comment by maidmeow4** [comment]
> 经核对日志发现，dnf 在请求上述包的时候，有的请求带了正确的 UA，有的请求没有 UA。后者触发了相关的屏蔽规则，因此返回了 403。

amazing 🤣

**Comment by shankerwangmiao** [comment]
> 恐怕又是 zchunk 的 bug？可以去 https://github.com/zchunk/zchunk 提一下（

怎么说？为啥是它的 bug？

**Comment by shankerwangmiao** [comment]
> > 经核对日志发现，dnf 在请求上述包的时候，有的请求带了正确的 UA，有的请求没有 UA。后者触发了相关的屏蔽规则，因此返回了 403。
> 
> amazing 🤣

能提供一下相应时间的 `/var/log/dnf.log` 吗？

**Comment by shankerwangmiao** [comment]
还有 `/var/log/dnf.librepo.log`

**Comment by maidmeow4** [comment]
log乱成一团不知道截的对不对 :rofl: 

<details>
  <summary>截了一下的 dnf.log </summary>

```
2021-08-17T11:48:44+0800 SUBDEBUG 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dnf/cli/cli.py", line 229, in do_transaction
    self.download_packages(install_pkgs, self.output.progress, total_cb)
  File "/usr/lib/python3.9/site-packages/dnf/base.py", line 1240, in download_packages
    self._download_remote_payloads(payloads, drpm, progress, callback_total)
  File "/usr/lib/python3.9/site-packages/dnf/base.py", line 1169, in _download_remote_payloads
    raise dnf.exceptions.DownloadError(errors._irrecoverable)
dnf.exceptions.DownloadError: Cannot download Packages/k/kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm: All mirrors were tried

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dnf/cli/main.py", line 67, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.9/site-packages/dnf/cli/main.py", line 106, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.9/site-packages/dnf/cli/main.py", line 130, in cli_run
    ret = resolving(cli, base)
  File "/usr/lib/python3.9/site-packages/dnf/cli/main.py", line 176, in resolving
    base.do_transaction(display=displays)
  File "/usr/lib/python3.9/site-packages/dnf/cli/cli.py", line 236, in do_transaction
    raise dnf.exceptions.Error(errstr)
dnf.exceptions.Error: 下载软件包出错 :
  Cannot download Packages/k/kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm: All mirrors were tried
2021-08-17T11:48:44+0800 CRITICAL 错误：下载软件包出错 :
  Cannot download Packages/k/kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm: All mirrors were tried
```

</details>

---

<details>
  <summary>截了一下的 dnf.librepo.log</summary>

```
2021-08-17T11:48:01+0800 INFO Downloading: https://codecs.fedoraproject.org/openh264/33/x86_64/os/repodata/fa9f31c08821f824e9371eeeb918aa00385d9d865ccfd6d54fb996dcc50a6830-primary.xml.gz
2021-08-17T11:48:01+0800 INFO Downloading: https://codecs.fedoraproject.org/openh264/33/x86_64/os/repodata/47753f30191e677ffc6d20cc5baf9eeec85e6c9b09b4ee5d7fe4c09ebea4f372-filelists.xml.gz
2021-08-17T11:48:01+0800 INFO Downloading: https://codecs.fedoraproject.org/openh264/33/x86_64/os/repodata/3d50825fb25440abc9579f078205d6ba3590b1d146187af8179eb43214c8b40e-comps-Temporary.x86_64.xml.gz
2021-08-17T11:48:09+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/releases/33/Modular/x86_64/os/repodata/repomd.xml
2021-08-17T11:48:10+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/releases/33/Modular/x86_64/os/repodata/3d4495b479c01f0ffbfbe65ff53e937bc828a7342e4a52509980a65396479ce0-primary.xml.zck
2021-08-17T11:48:10+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/releases/33/Modular/x86_64/os/repodata/8822bb340f6468ef580929c7a224898bbd9535017a0b67ed95de0e563d37b926-filelists.xml.zck
2021-08-17T11:48:10+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/releases/33/Modular/x86_64/os/repodata/7e241ed6bae47ebc55de9daf5d1152750d3320f325175a87780b22f07afddd04-comps-Modular.x86_64.xml
2021-08-17T11:48:10+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/releases/33/Modular/x86_64/os/repodata/3d4495b479c01f0ffbfbe65ff53e937bc828a7342e4a52509980a65396479ce0-primary.xml.zck
2021-08-17T11:48:10+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/releases/33/Modular/x86_64/os/repodata/8822bb340f6468ef580929c7a224898bbd9535017a0b67ed95de0e563d37b926-filelists.xml.zck
2021-08-17T11:48:10+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/releases/33/Modular/x86_64/os/repodata/0f96dbbd49227488dd3d57f88e200a2e8f3b2b373f158fa417d38aba63a031c5-modules.yaml.gz
2021-08-17T11:48:11+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/repodata/repomd.xml
2021-08-17T11:48:12+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/repodata/bf927e6407b3acef98d354b6560055a475ff14736a54edb1e0342eaafb8928bf-primary.xml.zck
2021-08-17T11:48:12+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/repodata/1721c232ad19ed69e528d2cfe9d40fee3b920693bd1f4e89d511db8879dc7e28-filelists.xml.zck
2021-08-17T11:48:12+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/repodata/3cfd9fc8028e4415fdb5cd62615532fd9a759c0d5656a5442ba76f88d52f5c0b-comps-Everything.x86_64.xml.gz
2021-08-17T11:48:12+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/repodata/bf927e6407b3acef98d354b6560055a475ff14736a54edb1e0342eaafb8928bf-primary.xml.zck
2021-08-17T11:48:12+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/repodata/1721c232ad19ed69e528d2cfe9d40fee3b920693bd1f4e89d511db8879dc7e28-filelists.xml.zck
2021-08-17T11:48:13+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/repodata/be467f9ffc165948d7f6bcf1055ca2da53aa04af7018eb69bb749ddee8d10f23-prestodelta.xml.zck
2021-08-17T11:48:13+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/repodata/30b95aefa7e2ec0091b7d9c1b5aa407cd0df52a6bddbf55e10bda54bd20ecc32-updateinfo.xml.zck
2021-08-17T11:48:13+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/repodata/30b95aefa7e2ec0091b7d9c1b5aa407cd0df52a6bddbf55e10bda54bd20ecc32-updateinfo.xml.zck
2021-08-17T11:48:25+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Modular/x86_64/repodata/repomd.xml
2021-08-17T11:48:25+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Modular/x86_64/repodata/3797d82bfb0477e35efcdc25967fc8642b3a83c5578816ae896066c36d2e1e17-primary.xml.zck
2021-08-17T11:48:25+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Modular/x86_64/repodata/9137dd8a35a911f3533722cb9d4c01c3ac920392078302395401fc7d8a3e4331-filelists.xml.zck
2021-08-17T11:48:25+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Modular/x86_64/repodata/c5478ca6745292346b9ae10b8fc9f2d2751c5da145822de26c5661859e815b8e-modules.yaml.gz
2021-08-17T11:48:25+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Modular/x86_64/repodata/3797d82bfb0477e35efcdc25967fc8642b3a83c5578816ae896066c36d2e1e17-primary.xml.zck
2021-08-17T11:48:25+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Modular/x86_64/repodata/9137dd8a35a911f3533722cb9d4c01c3ac920392078302395401fc7d8a3e4331-filelists.xml.zck
2021-08-17T11:48:26+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Modular/x86_64/repodata/b26297b7af24add073dfc87c613c6fb0f01e974b4523bdb2db9e8a582a025004-updateinfo.xml.zck
2021-08-17T11:48:26+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Modular/x86_64/repodata/b26297b7af24add073dfc87c613c6fb0f01e974b4523bdb2db9e8a582a025004-updateinfo.xml.zck
2021-08-17T11:48:27+0800 INFO Downloading: https://download.opensuse.org/repositories/home:/zzndb:/Qv2ray/Fedora_33/repodata/repomd.xml
2021-08-17T11:48:28+0800 INFO Downloading: https://download.opensuse.org/repositories/home:/zzndb:/Qv2ray/Fedora_33/repodata/ce6a21b0a75bf3bc8f63aa824f390fe7a2e99caa57de30103261d521bfc641a7-primary.xml.gz
2021-08-17T11:48:28+0800 INFO Downloading: https://download.opensuse.org/repositories/home:/zzndb:/Qv2ray/Fedora_33/repodata/b70bdf5ec4de5ae9075b851a24a5e6cbbf2e2fb4289091ee16214a327db5cde1-filelists.xml.gz
2021-08-17T11:48:32+0800 INFO Downloading: https://mirrors.tuna.tsinghua.edu.cn/rpmfusion/free/fedora/releases/33/Everything/x86_64/os/repodata/repomd.xml
2021-08-17T11:48:32+0800 INFO Downloading: https://mirrors.tuna.tsinghua.edu.cn/rpmfusion/free/fedora/releases/33/Everything/x86_64/os/repodata/d16b8486b83d83fd06aa0c33255a65f0c28402a8b332970bd20c7e31e5434398-filelists.xml.gz
2021-08-17T11:48:32+0800 INFO Downloading: https://mirrors.tuna.tsinghua.edu.cn/rpmfusion/free/fedora/releases/33/Everything/x86_64/os/repodata/dbccb8e62d15028a0c13138f86cc80b3624eb92ae7e354d1d4b6267b3863e6e9-comps-f33.xml.xz
2021-08-17T11:48:32+0800 INFO Downloading: https://mirrors.tuna.tsinghua.edu.cn/rpmfusion/free/fedora/releases/33/Everything/x86_64/os/repodata/b95e7e822d426fcffe417302dc33e2109b34a403c9a5d0f317421aa18d1a41aa-primary.xml.gz
2021-08-17T11:48:33+0800 INFO Downloading: https://mirrors.tuna.tsinghua.edu.cn/rpmfusion/free/fedora/updates/33/x86_64/repodata/repomd.xml
2021-08-17T11:48:34+0800 INFO Downloading: https://mirrors.tuna.tsinghua.edu.cn/rpmfusion/free/fedora/updates/33/x86_64/repodata/6a7c7a96301164efefc7c23b1e8dad7859a8464180bf7aa6c318cd1e1a84068a-filelists.xml.gz
2021-08-17T11:48:34+0800 INFO Downloading: https://mirrors.tuna.tsinghua.edu.cn/rpmfusion/free/fedora/updates/33/x86_64/repodata/dbccb8e62d15028a0c13138f86cc80b3624eb92ae7e354d1d4b6267b3863e6e9-comps-f33.xml.xz
2021-08-17T11:48:34+0800 INFO Downloading: https://mirrors.tuna.tsinghua.edu.cn/rpmfusion/free/fedora/updates/33/x86_64/repodata/db1eb18d1d9ff6ea4917100bbd0a353dd136f65f0056bcc6e72dc52558a53e12-primary.xml.gz
2021-08-17T11:48:44+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/releases/33/Everything/x86_64/os/Packages/l/libsodium-1.0.18-6.fc33.x86_64.rpm
2021-08-17T11:48:44+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/releases/33/Everything/x86_64/os/Packages/p/python3-packaging-20.4-2.fc33.noarch.rpm
2021-08-17T11:48:44+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/releases/33/Everything/x86_64/os/Packages/p/python3-pyparsing-2.4.7-4.fc33.noarch.rpm
2021-08-17T11:48:44+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/releases/33/Everything/x86_64/os/Packages/p/python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm
2021-08-17T11:48:44+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/Packages/k/kernel-devel-5.13.9-100.fc33.x86_64.rpm
2021-08-17T11:48:44+0800 INFO Error during transfer: Status code: 403 for https://mirrors.bfsu.edu.cn/fedora/releases/33/Everything/x86_64/os/Packages/p/python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm (IP: 2001:da8:20f:4435:4adf:37ff:fe55:2840)
2021-08-17T11:48:44+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/releases/33/Everything/x86_64/os/Packages/p/python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm
2021-08-17T11:48:44+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/Packages/k/kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm
2021-08-17T11:48:44+0800 INFO Error during transfer: Status code: 403 for https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/Packages/k/kernel-devel-5.13.9-100.fc33.x86_64.rpm (IP: 2001:da8:20f:4435:4adf:37ff:fe55:2840)
2021-08-17T11:48:44+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/Packages/k/kernel-devel-5.13.9-100.fc33.x86_64.rpm
2021-08-17T11:48:44+0800 INFO Error during transfer: Status code: 403 for https://mirrors.bfsu.edu.cn/fedora/releases/33/Everything/x86_64/os/Packages/p/python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm (IP: 2001:da8:20f:4435:4adf:37ff:fe55:2840)
2021-08-17T11:48:44+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/releases/33/Everything/x86_64/os/Packages/p/python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm
2021-08-17T11:48:44+0800 INFO Error during transfer: Status code: 403 for https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/Packages/k/kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm (IP: 2001:da8:20f:4435:4adf:37ff:fe55:2840)
2021-08-17T11:48:44+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/Packages/k/kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm
2021-08-17T11:48:44+0800 INFO Error during transfer: Status code: 403 for https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/Packages/k/kernel-devel-5.13.9-100.fc33.x86_64.rpm (IP: 2001:da8:20f:4435:4adf:37ff:fe55:2840)
2021-08-17T11:48:44+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/Packages/k/kernel-devel-5.13.9-100.fc33.x86_64.rpm
2021-08-17T11:48:44+0800 INFO Error during transfer: Status code: 403 for https://mirrors.bfsu.edu.cn/fedora/releases/33/Everything/x86_64/os/Packages/p/python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm (IP: 2001:da8:20f:4435:4adf:37ff:fe55:2840)
2021-08-17T11:48:44+0800 INFO Downloading: https://mirrors.bfsu.edu.cn/fedora/releases/33/Everything/x86_64/os/Packages/p/python3-simpleaudio-1.0.4-2.fc33.x86_64.rpm
2021-08-17T11:48:44+0800 INFO Error during transfer: Status code: 403 for https://mirrors.bfsu.edu.cn/fedora/updates/33/Everything/x86_64/Packages/k/kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm (IP: 2001:da8:20f:4435:4adf:37ff:fe55:2840)
2021-08-17T11:48:44+0800 INFO Error while downloading: Cannot download Packages/k/kernel-modules-extra-5.13.9-100.fc33.x86_64.rpm: All mirrors were tried
```

</details>

**Comment by shankerwangmiao** [comment]
求一下完整的 dnf.log，不是要看 traceback

**Comment by maidmeow4** [comment]
[logs.zip](https://github.com/tuna/issues/files/6998642/logs.zip)

**Comment by lch** [comment]
`/var/log/dnf.log` 中已经输出了正确的 `User-Agent`，并且对元数据和部分包的请求也使用了正确的 `User-Agent`。dnf 使用 librepo 进行 rpm 的下载，因此问题有可能出在 dnf 的依赖 librepo 中。首先可以尝试重新安装 librepo ，并检查问题是否解决。

由于 librepo 默认情况下只会输出 INFO 级别的日志于 `/var/log/dnf.librepo.log`，可以尝试将 dnf 的 loglevel 设置为 10，然后再查看 `/var/log/dnf.librepo.log` 是否有更详细的输出以便排查。不过此处即便设置以最高的 loglevel 10，也可能并不会在日志中直接输出 librepo 用于请求的 `User-Agent`。
`/etc/dnf/dnf.conf`
```
[main]
logfilelevel=10
```

**Comment by liusen373** [comment]
@skyzh 这个问题应该与zchunk无关，zchunk只下载rpm仓库中的软件包索引，不下载具体的rpm。

**Comment by maidmeow4** [comment]
用 `sudo dnf reinstall librepo` 后问题依旧

设置了 `logfilelevel=10`后的 `dnf.librepo.log` （从操作开始时裁掉了此前的部分）
[cut_dnf.librepo.log](https://github.com/tuna/issues/files/7000698/cut_dnf.librepo.log)
