### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://mirror.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch/current_repodata.json

### ISSUE THREAD

**Issue by dancahda** [tuna/issues#1574]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

/home/chendan/miniconda3/bin/conda update conda
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 719, in fetch_repodata_remote_request
        resp.raise_for_status()
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://mirror.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch/current_repodata.json
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/requests/models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
        return _default_decoder.decode(s)
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
        obj, end = self.raw_decode(s)
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1125, in __call__
        return func(*args, **kwargs)
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/notices/core.py", line 72, in wrapper
        return_value = func(*args, **kwargs)
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/cli/main_update.py", line 22, in execute
        install(args, parser, 'update')
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 256, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 195, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 300, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 86, in decorated
        return f(*args, **kwds)
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 463, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 1057, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/core/index.py", line 297, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 152, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/home/chendan/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
        yield fs.pop().result()
      File "/home/chendan/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 432, in result
        return self.__get_result()
      File "/home/chendan/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
        raise self._exception
      File "/home/chendan/miniconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 144, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 157, in query
        self.load()
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 222, in load
        _internal_state = self._load()
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 387, in _load
        raw_repodata_str = fetch_repodata_remote_request(
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 775, in fetch_repodata_remote_request
        raise UnavailableInvalidChannel(
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 460, in __init__
        body = response.json()
      File "/home/chendan/miniconda3/lib/python3.8/site-packages/requests/models.py", line 975, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /home/chendan/miniconda3/bin/conda update conda`

  environment variables:
                 CIO_TEST=<not set>
        CMAKE_PREFIX_PATH=/home/chendan/miniconda3:/home/chendan/miniconda3/x86_64-conda_cos6-li
                          nux-gnu/sysroot/usr
        CONDA_BACKUP_HOST=x86_64-conda_cos6-linux-gnu
   CONDA_BACKUP_JAVA_HOME=
CONDA_BACKUP_JAVA_LD_LIBRARY_PATH=
      CONDA_BUILD_SYSROOT=/home/chendan/miniconda3/x86_64-conda_cos6-linux-gnu/sysroot
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/chendan/miniconda3/bin/conda
             CONDA_PREFIX=/home/chendan/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/chendan/miniconda3/bin/python
               CONDA_ROOT=/home/chendan/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
     JAVA_LD_LIBRARY_PATH=/home/chendan/miniconda3/jre/lib/amd64/server
                     PATH=/home/chendan/miniconda3/bin:/home/chendan/miniconda3/condabin:/usr/lo
                          cal/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/
                          local/games:/snap/bin:/home/chendan/.local/bin:/home/chendan/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/chendan/miniconda3
            shell level : 1
       user config file : /home/chendan/.condarc
 populated config files : /home/chendan/.condarc
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __linux=4.4.0=0
                          __glibc=2.23=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/chendan/miniconda3  (writable)
      conda av data dir : /home/chendan/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : http://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/linux-64
                          http://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/noarch
                          http://mirror.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          http://mirror.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          http://mirror.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          http://mirror.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
          package cache : /home/chendan/miniconda3/pkgs
                          /home/chendan/.conda/pkgs
       envs directories : /home/chendan/miniconda3/envs
                          /home/chendan/.conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.28.1 CPython/3.8.5 Linux/4.4.0-116-generic ubuntu/16.04.4 glibc/2.23
                UID:GID : 1004:1014
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

Upload successful.

### 期望的现象（What you expected to happen）

solve this problem

### 如何重现此问题（How to reproduce it）

when I run the command: conda update conda , it always report the bugs above.

### 操作系统（OS Version）

 Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-116-generic x86_64)

### 其他环境（Other environments）

$ conda info

     active environment : None
            shell level : 0
       user config file : /home/chendan/.condarc
 populated config files : /home/chendan/.condarc
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __linux=4.4.0=0
                          __glibc=2.23=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/chendan/miniconda3  (writable)
      conda av data dir : /home/chendan/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : http://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/linux-64
                          http://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/noarch
                          http://mirror.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          http://mirror.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          http://mirror.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          http://mirror.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
          package cache : /home/chendan/miniconda3/pkgs
                          /home/chendan/.conda/pkgs
       envs directories : /home/chendan/miniconda3/envs
                          /home/chendan/.conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.28.1 CPython/3.8.5 Linux/4.4.0-116-generic ubuntu/16.04.4 glibc/2.23
                UID:GID : 1004:1014
             netrc file : None
           offline mode : False

$ cat /home/chendan/.condarc 
auto_activate_base: false
channels:
  - http://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/
  - http://mirror.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - http://mirror.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
show_channel_urls: true
report_errors: true
channel_priority: flexible
ssl_verify: false

**Comment by ZenithalHourlyRate** [comment]
https://github.com/tuna/issues/issues/1518#issuecomment-1169865221

**Comment by dancahda** [comment]
Thank you very much! It works!
