### ISSUE TITLE
dart-pub镜像不同步

### ISSUE THREAD

**Issue by 89ao** [tuna/issues#1605]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

<img width="862" alt="image" src="https://user-images.githubusercontent.com/5635923/197519019-be61957b-e173-48a7-a3f2-92a38b600ba9.png">
dart-pub镜像不同步

### 期望的现象（What you expected to happen）

不同步时间已持续2周，请协助支持

### 如何重现此问题（How to reproduce it）

https://mirrors.tuna.tsinghua.edu.cn/

**Comment by ZenithalHourlyRate** [comment]
dart-pub 由 [pub-mirror](https://github.com/tuna/pub-mirror) 同步，在同步中发现以下报错：

```
Unhandled exception:                                                            
type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast         
#0      _$ComplexDependencyFromJson (package:pub_client/src/models.g.dart:191:44)
#1      new ComplexDependency.fromJson (package:pub_client/src/models.dart:203:68)
#2      new Dependencies.fromJson.<anonymous closure> (package:pub_client/src/models.dart:117:55)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#4      new Dependencies.fromJson (package:pub_client/src/models.dart:110:10)   
#5      _$PubspecFromJson (package:pub_client/src/models.g.dart:111:26)         
#6      new Pubspec.fromJson (package:pub_client/src/models.dart:84:58)         
#7      _$VersionFromJson (package:pub_client/src/models.g.dart:83:21)          
#8      new Version.fromJson (package:pub_client/src/models.dart:64:58)         
#9      _$PackageFromJson (package:pub_client/src/models.g.dart:32:21)          
#10     new Package.fromJson (package:pub_client/src/models.dart:27:58)         
#11     _$PageFromJson.<anonymous closure> (package:pub_client/src/models.g.dart:14:42)
#12     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)         
#13     ListIterable.toList (dart:_internal/iterable.dart:221:19)               
#14     _$PageFromJson (package:pub_client/src/models.g.dart:15:13)             
#15     new Page.fromJson (package:pub_client/src/models.dart:11:55)            
#16     PubClient.getPageOfPackages (package:pub_client/pub_client.dart:59:22)  
<asynchronous suspension>                                                       
#17     PubMirrorTool.listAllPackages.<anonymous closure> (package:pub_mirror/pub_mirror.dart:76:14)
#18     RetryOptions.retry (package:retry/retry.dart:130:24)                    
#19     PubMirrorTool.listAllPackages (package:pub_mirror/pub_mirror.dart:73:52)
<asynchronous suspension>                                                       
#20     PubMirrorTool.download (package:pub_mirror/pub_mirror.dart:198:31)         
#21     main (file:///pub-cache/git/pub-mirror-d132872259de99d48b1229ea2b8a56ab6feba666/bin/pub_mirror.dart:47:8)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

可以注意到错误发生在依赖 [pub_client](https://github.com/jimsimon/pub_client) 中，具体体现在解析目前的 <https://pub.dartlang.org/api/packages?page=2> 时会遇到[两周前更新](https://github.com/GM-Consult-Pty-Ltd/oxford_dictionaries/commit/38f3c3ea41ecf26879d6f51659bfedfa42956385#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25)的如下软件包

```json
    {                                                                           
      "name": "oxford_dictionaries",                                            
      "latest": {                                                               
        "version": "0.0.1+2",                                                   
        "pubspec": {                                                                
          "name": "oxford_dictionaries",                                            
          "description": "Dictionary class that uses the Oxford Dictionaries RESTful API.",
          "version": "0.0.1+2",                                                     
          "repository": "https://github.com/GM-Consult-Pty-Ltd/oxford_dictionaries",
          "homepage": "https://github.com/GM-Consult-Pty-Ltd",                      
          "issue_tracker": "https://github.com/GM-Consult-Pty-Ltd/oxford_dictionaries/issues",
          "environment": {                                                      
            "sdk": ">=2.17.6 <3.0.0"                                            
          },                                                                    
          "dependencies": {                                                     
            "dictosaurus": "^0.0.21",                                           
            "gmconsult_dart_core": "^0.0.5",                                    
            "porter_2_stemmer": "^3.0.1"                                        
          },                                                                    
          "dev_dependencies": {                                                 
            "gmconsult_dev": "^0.0.7+4",                                        
            "gmconsult_proprietary": {                                          
              "version": "^0.0.1-5",                                            
              "hosted": "https://onepub.dev/api/jxxxpsdavu"                     
            },                                                                  
            "lints": "^2.0.0",                                                  
            "test": "^1.21.1"                                                   
          }                                                                         
        },                                                                          
        "archive_url": "https://pub.dartlang.org/packages/oxford_dictionaries/versions/0.0.1%2B2.tar.gz",
        "package_url": "https://pub.dartlang.org/api/packages/oxford_dictionaries",
        "url": "https://pub.dartlang.org/api/packages/oxford_dictionaries/versions/0.0.1%2B2"
      }                                                                         
    },                                                                          
    {                                                                           
      "name": "dictosaurus",                                                    
      "latest": {                                                               
        "version": "0.0.21",                                                    
        "pubspec": {                                                            
          "name": "dictosaurus",                                                    
          "description": "Dictionary, thesaurus and term expansion utilities used in natural language processing.",
          "version": "0.0.21",                                                      
          "repository": "https://github.com/GM-Consult-Pty-Ltd/dictosaurus",    
          "homepage": "https://github.com/GM-Consult-Pty-Ltd",                      
          "issue_tracker": "https://github.com/GM-Consult-Pty-Ltd/dictosaurus/issues",
          "environment": {                                                      
            "sdk": ">=2.17.6 <3.0.0"                                            
          },                                                                    
          "dependencies": {                                                     
            "collection": "^1.16.0",                                            
            "gmconsult_dart_core": "^0.0.5",                                    
            "meta": "^1.8.0",                                                   
            "text_analysis": "^0.20.0"                                          
          },                                                                    
          "dev_dependencies": {                                                 
            "gmconsult_dev": "^0.0.7+4",                                        
            "gmconsult_proprietary": {                                          
              "version": "^0.0.1-5",                                            
              "hosted": "https://onepub.dev/api/jxxxpsdavu"                     
            },                                                                  
            "hive": "^2.2.3",                                                   
            "lints": "^2.0.0",                                                  
            "test": "^1.21.1",                                                  
            "text_indexing": "^0.19.0"                                          
          }                                                                     
        },                                                                          
        "archive_url": "https://pub.dartlang.org/packages/dictosaurus/versions/0.0.21.tar.gz",
        "package_url": "https://pub.dartlang.org/api/packages/dictosaurus",         
        "url": "https://pub.dartlang.org/api/packages/dictosaurus/versions/0.0.21"
      }                                                                         
    },                                                                          
```

其中 `hosted` 为 `String` 而不是 `Map<String, dynamic>`

这是 pubspec 升级造成的，参考 <https://dart.dev/tools/pub/dependencies> 中对于 Hosted packages 的描述，有

> If you want to use your [own package repository](https://dart.dev/tools/pub/custom-package-repositories), you can use hosted to specify its URL. The following YAML code creates a dependency on the transmogrify package using the hosted source:
> ```yaml
>  hosted: https://some-package-server.com
> ```
> Version note: If your package has a [language version](https://dart.dev/guides/language/evolution#language-versioning) before 2.15, you must use a more verbose hosted format:
> ```yaml
> hosted:
>     name: transmogrify
>     url: https://some-package-server.com
> ```

由于 pub_client 不再维护，其替代品的 [pub_api_client](https://github.com/fluttertools/pub_api_client) 并没有下载软件包功能，需要自己维护 pub_client 以适应 pubspec 的变动

**Comment by ZenithalHourlyRate** [comment]
已经修复，正在同步中。
