### ISSUE TITLE
Conda cannot be used normally which may due to the website listed below which cannot be opened in those days.

### ISSUE THREAD

**Issue by luwd401** [tuna/issues#1863]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

The website "https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64/current_repodata.json" cannot be opened.

System: ubuntu 22.04LTS, terminal: conda update conda， conda cannot be used。反馈信息如下：

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/lu401/miniconda3/bin/conda
             CONDA_PREFIX=/home/lu401/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/lu401/miniconda3/bin/python
               CONDA_ROOT=/home/lu401/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/lu401/perl5/bin:/home/lu401/miniconda3/bin:/home/lu401/miniconda
                          3/condabin:/home/lu401/howard/btllib-
                          1.6.2/install/bin:/home/lu/howard/blast-
                          2.14/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:
                          /usr/games:/usr/local/games:/snap/bin:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /home/lu401/miniconda3
            shell level : 1
       user config file : /home/lu401/.condarc
 populated config files : /home/lu401/.condarc
          conda version : 23.5.2
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __glibc=2.35=0
                          __linux=6.2.0=0
                          __unix=0=0
       base environment : /home/lu401/miniconda3  (writable)
      conda av data dir : /home/lu401/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/lu401/miniconda3/pkgs
                          /home/lu401/.conda/pkgs
       envs directories : /home/lu401/miniconda3/envs
                          /home/lu401/.conda/envs
               platform : linux-64
             user-agent : conda/23.5.2 requests/2.29.0 CPython/3.11.4 Linux/6.2.0-37-generic ubuntu/22.04.3 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

Upload successful.

Second：terminal: conda create -n Trinotate

Collecting package metadata (current_repodata.json): done
Solving environment: done

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 187, in conda_http_errors
        yield
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 153, in repodata
        response.raise_for_status()
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64/current_repodata.json
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/requests/models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
        obj, end = self.raw_decode(s)
                   ^^^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/cli/main.py", line 84, in main_subshell
        exit_code = do_call(args, p)
                    ^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 126, in do_call
        return getattr(module, func_name)(args, parser)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/notices/core.py", line 123, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/cli/main_create.py", line 46, in execute
        install(args, parser, "create")
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/cli/install.py", line 309, in install
        unlink_link_transaction = solver.solve_for_transaction(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/core/solve.py", line 173, in solve_for_transaction
        self._notify_conda_outdated(link_precs)
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/core/solve.py", line 1223, in _notify_conda_outdated
        SubdirData.query_all(
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/core/subdir_data.py", line 157, in query_all
        result = tuple(
                 ^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
        yield _result_or_cancel(fs.pop())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
        return fut.result(timeout)
               ^^^^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 456, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
        raise self._exception
      File "/home/lu401/miniconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/core/subdir_data.py", line 142, in subdir_query
        return tuple(
               ^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/core/subdir_data.py", line 164, in query
        self.load()
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/core/subdir_data.py", line 264, in load
        _internal_state = self._load()
                          ^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/core/subdir_data.py", line 321, in _load
        repodata, state = fetcher.fetch_latest_parsed()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 757, in fetch_latest_parsed
        parsed, state = self.fetch_latest()
                        ^^^^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 879, in fetch_latest
        raw_repodata = repo.repodata(cache.state)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 143, in repodata
        with conda_http_errors(self._url, filename):
      File "/home/lu401/miniconda3/lib/python3.11/contextlib.py", line 155, in __exit__
        self.gen.throw(typ, value, traceback)
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 234, in conda_http_errors
        raise RepodataIsEmpty(
              ^^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/conda/exceptions.py", line 527, in __init__
        body = response.json()
               ^^^^^^^^^^^^^^^
      File "/home/lu401/miniconda3/lib/python3.11/site-packages/requests/models.py", line 975, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### 期望的现象（What you expected to happen）

(1) The website "https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64/current_repodata.json" can be opened.
(2) Conda can be used normally

### 如何重现此问题（How to reproduce it）

typing"conda update conda" in the terminal， conda cannot be used normally。

### 操作系统（OS Version）

ubuntu 22.04LTS

**Comment by shankerwangmiao** [comment]
`current_repodata.json` 文件我们从未提供过，它的缺失应该不影响 conda 的正常使用。

**Comment by Harry-Chen** [comment]
真正的问题应该是

> simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

可以考虑从此入手检查

**Comment by luwd401** [comment]
谢谢回复。具体如何检查，根据目前提示的信息，是否重新安装conda能解决问题？

--------------原始邮件--------------
发件人："Shengqi&nbsp;Chen ***@***.***&gt;;
发送时间：2023年12月21日(星期四) 中午12:51
收件人："tuna/issues" ***@***.***&gt;;
抄送："weidonglu ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [tuna/issues] Conda cannot be used normally which may due to the website listed below which cannot be opened in those days. (Issue #1863)
-----------------------------------

 

 
真正的问题应该是
  
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  
可以考虑从此入手检查
