### ISSUE TITLE
北外的anaconda源安装报错

### ISSUE THREAD

**Issue by jackiehope** [tuna/issues#1932]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

使用conda创建环境时报错
```
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

PackagesNotFoundError: The following packages are not available from current channels:

  - python=3.8.10

Current channels:

  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/msys2/linux-64
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/msys2/noarch
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/linux-64
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/noarch
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/linux-64
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org
```

### 期望的现象（What you expected to happen）

正常创建conda环境

### 如何重现此问题（How to reproduce it）

conda create -n myenv python=3.8.10

### 其他需要说明的事项（Anything else we need to know）

看了下网页内容，python的3.8.10包是存在的，但仓库索引文件版本比清华源的旧，怀疑是这个地方有问题，目前切换到清华源以后可以使用。
```
[current_repodata.json](https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/linux-64/current_repodata.json)	7.4 MiB	2024-04-06 04:00
```
```
[current_repodata.json](https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/current_repodata.json)	7.4 MiB	2024-04-09 06:11
```
我是通过北外网页底下的链接到这个仓库的，没有搜到北外的联系方式，如能联系到帮忙反馈下

**Comment by jackiehope** [comment]
执行`conda search python`有报错
```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.10/site-packages/conda/auxlib/logz.py", line 165, in stringify
    requests_models_Response_builder(builder, obj)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.10/site-packages/conda/auxlib/logz.py", line 141, in requests_models_Response_builder
    resp = response_object.json()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
done
No match found for: python. Search: *python*
# Name                       Version           Build  Channel
r-findpython                   1.0.5   r36h6115d3f_0  anaconda/pkgs/r
r-findpython                   1.0.7   r42h6115d3f_0  anaconda/pkgs/r
r-findpython                   1.0.8   r43h6115d3f_0  anaconda/pkgs/r
```

**Comment by jackiehope** [comment]
执行`conda search python`有报错
```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.10/site-packages/conda/auxlib/logz.py", line 165, in stringify
    requests_models_Response_builder(builder, obj)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.10/site-packages/conda/auxlib/logz.py", line 141, in requests_models_Response_builder
    resp = response_object.json()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
done
No match found for: python. Search: *python*
# Name                       Version           Build  Channel
r-findpython                   1.0.5   r36h6115d3f_0  anaconda/pkgs/r
r-findpython                   1.0.7   r42h6115d3f_0  anaconda/pkgs/r
r-findpython                   1.0.8   r43h6115d3f_0  anaconda/pkgs/r
```

**Comment by shankerwangmiao** [comment]
请您再用 BFSU 测试一次？

**Comment by jackiehope** [comment]
重新测试了一下，BFSU还是不行，已经执行过`conda clean -i`

**Comment by jackiehope** [comment]
![image](https://github.com/tuna/issues/assets/13598251/f7049387-1104-4d3d-8fa6-f37aed658dd5)
看BFSU的linux-64下的repodata还是旧的

**Comment by jackiehope** [comment]
![image](https://github.com/tuna/issues/assets/13598251/af49cf0a-477b-4875-aef5-6c6ccafa3c33)
BFSU有个gz的文件是空的，在TUNA源里面是正常的，可能json load失败和这个有关
![image](https://github.com/tuna/issues/assets/13598251/4cd172f8-b0a3-456a-8dc5-bafaeb61aade)

**Comment by chen-jie-h** [comment]
```
Collecting package metadata (repodata.json): - \ | / - \ | / - \ | / - \ | / - \ | ERROR conda.auxlib.logz:stringify(171): Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/conda/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
我用清华源安装依赖也是这个报错，昨天执行安装还没有问题，今天早上到现在一直是这个报错，请问解决了吗

**Comment by jackiehope** [comment]
> ```
> Collecting package metadata (repodata.json): - ��\ ��| ��/ ��- ��\ ��| ��/ ��- ��\ ��| ��/ ��- ��\ ��| ��/ ��- ��\ ��| ERROR conda.auxlib.logz:stringify(171): Expecting value: line 1 column 1 (char 0)
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 971, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/opt/conda/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/opt/conda/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/opt/conda/lib/python3.10/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> 我用清华源安装依赖也是这个报错，昨天执行安装还没有问题，今天早上到现在一直是这个报错，请问解决了吗
你是不是用到了custom channel，我用的default channel清华源是正常的

**Comment by shankerwangmiao** [comment]
我这边看，目前文件都是好的

<img width="1163" alt="image" src="https://github.com/tuna/issues/assets/6825907/dfb0bdab-a342-44b3-8350-b50b404c5a76">

**Comment by shankerwangmiao** [comment]
您能设法在服务器上输出下载到的 `repodata.json` 文件吗？

**Comment by jackiehope** [comment]
刚测试了一下BSFU源，现在能正常search到数据了，看来是问题已经修复，感谢
