### ISSUE TITLE
conda-forge 镜像报错 RuntimeError: Unable to read repodata JSON file

### ISSUE THREAD

**Issue by Cloudac7** [tuna/issues#2053]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

我尝试使用 `conda install` 安装软件，但加载 repodata 时出现了如下的报错，因而软件无法安装：

```bash
$ conda install -c conda-forge phonopy
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/public/home/ypliucat/miniforge3/lib/python3.12/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/public/home/ypliucat/miniforge3/lib/python3.12/site-packages/conda/cli/main.py", line 84, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/public/home/ypliucat/miniforge3/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 200, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/public/home/ypliucat/miniforge3/lib/python3.12/site-packages/conda/notices/core.py", line 132, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/public/home/ypliucat/miniforge3/lib/python3.12/site-packages/conda/cli/main_install.py", line 152, in execute
        return install(args, parser, "install")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/public/home/ypliucat/miniforge3/lib/python3.12/site-packages/conda/cli/install.py", line 383, in install
        unlink_link_transaction = solver.solve_for_transaction(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/public/home/ypliucat/miniforge3/lib/python3.12/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
                                   ^^^^^^^^^^^^^^^^^^^^
      File "/public/home/ypliucat/miniforge3/lib/python3.12/site-packages/conda/core/solve.py", line 221, in solve_for_diff
        final_precs = self.solve_final_state(
                      ^^^^^^^^^^^^^^^^^^^^^^^
      File "/public/home/ypliucat/miniforge3/lib/python3.12/site-packages/conda_libmamba_solver/solver.py", line 207, in solve_final_state
        index = IndexHelper(
                ^^^^^^^^^^^^
      File "/public/home/ypliucat/miniforge3/lib/python3.12/site-packages/conda_libmamba_solver/index.py", line 136, in __init__
        self._index = self._load_channels()
                      ^^^^^^^^^^^^^^^^^^^^^
      File "/public/home/ypliucat/miniforge3/lib/python3.12/site-packages/conda_libmamba_solver/index.py", line 339, in _load_channels
        info = self._json_path_to_repo_info(url, jsons[url])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/public/home/ypliucat/miniforge3/lib/python3.12/site-packages/conda_libmamba_solver/index.py", line 295, in _json_path_to_repo_info
        repo = api.Repo(self._pool, noauth_url, str(path_to_use), escape_channel_url(noauth_url))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    RuntimeError: Unable to read repodata JSON file 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64', error was: parse error line 1

`$ /public/home/ypliucat/miniforge3/bin/conda install -c conda-forge phonopy`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=/public/groups/chenggroup/libs/phonopy-2.28
                CONDA_EXE=/public/home/ypliucat/miniforge3/bin/conda
             CONDA_PREFIX=/public/groups/chenggroup/libs/phonopy-2.28
           CONDA_PREFIX_1=/public/home/ypliucat/miniforge3
    CONDA_PROMPT_MODIFIER=(/public/groups/chenggroup/libs/phonopy-2.28)
         CONDA_PYTHON_EXE=/public/home/ypliucat/miniforge3/bin/python
               CONDA_ROOT=/public/home/ypliucat/miniforge3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                  MANPATH=:
               MODULEPATH=/public/modulefiles:/public/software/intel/oneapi2021/modulefiles:/pub
                          lic/modulefiles/misc:/public/ikkem
                     PATH=/public/groups/chenggroup/libs/phonopy-
                          2.28/bin:/public/home/ypliucat/miniforge3/condabin:/usr/lib64/qt-
                          3.3/bin:/public/software/Modules-5.2.0/bin:/public/software/Modules-
                          4.5.0/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/
                          ibutils/bin:/public/home/ypliucat/.local/bin:/public/home/ypliucat/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : /public/groups/chenggroup/libs/phonopy-2.28
    active env location : /public/groups/chenggroup/libs/phonopy-2.28
            shell level : 2
       user config file : /public/home/ypliucat/.condarc
 populated config files : /public/home/ypliucat/miniforge3/.condarc
                          /public/home/ypliucat/.condarc
          conda version : 24.7.1
    conda-build version : not installed
         python version : 3.12.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake_avx512
                          __conda=24.7.1=0
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /public/home/ypliucat/miniforge3  (writable)
      conda av data dir : /public/home/ypliucat/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : /public/home/ypliucat/miniforge3/pkgs
                          /public/home/ypliucat/.conda/pkgs
       envs directories : /public/home/ypliucat/miniforge3/envs
                          /public/home/ypliucat/.conda/envs
               platform : linux-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.12.5 Linux/3.10.0-862.el7.x86_64 centos/7.5.1804 glibc/2.17 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.9
                UID:GID : 32601:42103
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: y
Upload did not complete.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true
```

当取消TUNA镜像采用官方索引时，可以正确安装软件。

### 期望的现象（What you expected to happen）

运行 `conda install` 时可以正确安装，就像不使用镜像时的那样。

### 如何重现此问题（How to reproduce it）

在 `~/.condarc` 中启用 TUNA 镜像，确保 conda-forge 在镜像列表中:
```yaml
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

运行 `conda clean -i` 清除索引缓存，保证用的是镜像站提供的索引。然后创建虚拟环境并安装任意软件，例如：
```bash
conda create -n myenv python=3.10
```

### 操作系统（OS Version）

CentOS 7

**Comment by Harry-Chen** [comment]
请给出您的 condarc 配置。

**Comment by Cloudac7** [comment]
> 请给出您的 condarc 配置。

```yaml
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

**Comment by Harry-Chen** [comment]
请尝试是否可用 curl 等工具访问 `https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/repodata.json.zst`，如果不能，给出相应的异常内容。

**Comment by Cloudac7** [comment]
> 请尝试是否可用 curl 等工具访问 `https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/repodata.json.zst`，如果不能，给出相应的异常内容。

可以正确访问并下载上述 zst 文件

**Comment by zzy9001** [comment]
> > 请尝试是否可用 curl 等工具访问 `https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/repodata.json.zst`，如果不能，给出相应的异常内容。
> 
> 可以正确访问并下载上述 zst 文件

可以试着check下，下载的文件是否正常么，我这边是这样的情况
![image](https://github.com/user-attachments/assets/f53e08b7-13b1-4843-bd7a-288d85326b21)

![image](https://github.com/user-attachments/assets/b7bf0dcd-acc2-40c5-a7fe-660224f30489)

**Comment by Harry-Chen** [comment]
@Cloudac7 @zzy9001 请测试一下，是否能正常使用。上述的 repodata.json.zst 在同步过程中损坏，目前已经重新同步

**Comment by zzy9001** [comment]
> @Cloudac7 @zzy9001 请测试一下，是否能正常使用。上述的 repodata.json.zst 在同步过程中损坏，目前已经重新同步
测试ok了可以正常install,感谢

**Comment by Cloudac7** [comment]
> > > 请尝试是否可用 curl 等工具访问 `https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/repodata.json.zst`，如果不能，给出相应的异常内容。
> > 
> > 
> > 可以正确访问并下载上述 zst 文件
> 
> 可以试着check下，下载的文件是否正常么，我这边是这样的情况 ![image](https://private-user-images.githubusercontent.com/165634633/375203795-f53e08b7-13b1-4843-bd7a-288d85326b21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzE4NzksIm5iZiI6MTcyODUzMTU3OSwicGF0aCI6Ii8xNjU2MzQ2MzMvMzc1MjAzNzk1LWY1M2UwOGI3LTEzYjEtNDg0My1iZDdhLTI4OGQ4NTMyNmIyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwMzM5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTgyYTc2ZjdiMjJhNWVlNmRiYTk4OWMxOWQ3MDIwZDhjNGU3OGZkYjI3ZjMzZTdiMGYzZjY3NDYyMzA3YTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G_1U1sXh3TzPf5z27gR0raMHklG37i_8SAXBEqs5JEY)
> 
> ![image](https://private-user-images.githubusercontent.com/165634633/375204088-b7bf0dcd-acc2-40c5-a7fe-660224f30489.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzE4NzksIm5iZiI6MTcyODUzMTU3OSwicGF0aCI6Ii8xNjU2MzQ2MzMvMzc1MjA0MDg4LWI3YmYwZGNkLWFjYzItNDBjNS1hN2ZlLTY2MDIyNGYzMDQ4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwMzM5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjFkYmNjZTA2NGY3YzkwMzU2ZDM3NTJiMjQ1ZTYwNjUxNzI2Yjc2OWRlY2MzOTY0ZmM0MjU2ODhiNmJjMmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tEa86FgbGC8UBOssuhfKXi9KvZ0jYO27xpsekrU-Mdo)

确实是一样的issue，`repodata.json` 损坏了

```
$ zstd -t repodata.json.zst
repodata.json.zst    : 0 B...     repodata.json.zst : Read error (39) : premature end
```

**Comment by Cloudac7** [comment]
> @Cloudac7 @zzy9001 请测试一下，是否能正常使用。上述的 repodata.json.zst 在同步过程中损坏，目前已经重新同步

非常感谢，已恢复正常，`conda` 可以正确读取 repodata，`zstd` 也不会报错。

```
$ curl https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/repodata.json.zst | zstd -t
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 37.0M  100 37.0M    0     0  21.7M      0  0:00:01  0:00:01 --:--:-- 21.7M
/*stdin*\           : 293436148 bytes
```
