### ISSUE TITLE
Anaconda源提供的TensorFlow有部分代码缺漏

### ISSUE THREAD

**Issue by sandyzikun** [tuna/issues#537]
在`IPython`中输入

```py
>>> import tensorflow as tf
```

会报错：

```py
ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors for some common reasons and solutions.  Include the entire stack trace above this error message when asking for help.
```

希望能抽空解决一下这些问题吧，看看是不是少了什么包之类的，谢谢。

**Comment by z4yx** [comment]
关于停止Anaconda镜像服务的通知 https://mirrors.tuna.tsinghua.edu.cn/news/close-anaconda-service/

**Comment by sandyzikun** [comment]
额好吧谢谢。应该是好的，但是非常慢，一中午都装不完一个`TensorFlow_Base`

**Comment by z4yx** [comment]
今天安装测试了一下是正常的。怀疑与 #701 有关。

```
_tflow_select:        2.1.0-gpu                
absl-py:              0.9.0-py37_0             
asn1crypto:           1.3.0-py37_0             
astor:                0.8.0-py37_0             
blas:                 1.0-mkl                  
blinker:              1.4-py37_0               
ca-certificates:      2020.1.1-0               
cachetools:           3.1.1-py_0               
certifi:              2019.11.28-py37_0        
cffi:                 1.14.0-py37h7a1dbc1_0    
chardet:              3.0.4-py37_1003          
click:                7.0-py_0                 
cryptography:         2.8-py37h7a1dbc1_0       
cudatoolkit:          10.1.243-h74a9793_0      
cudnn:                7.6.5-cuda10.1_0         
gast:                 0.2.2-py37_0             
google-auth:          1.11.2-py_0              
google-auth-oauthlib: 0.4.1-py_2               
google-pasta:         0.1.8-py_0               
grpcio:               1.27.2-py37h351948d_0    
h5py:                 2.10.0-py37h5e291fa_0    
hdf5:                 1.10.4-h7ebc959_0        
icc_rt:               2019.0.0-h0cc432a_1      
idna:                 2.8-py37_0               
intel-openmp:         2020.0-166               
keras-applications:   1.0.8-py_0               
keras-preprocessing:  1.1.0-py_1               
libprotobuf:          3.11.4-h7bd577a_0        
markdown:             3.1.1-py37_0             
mkl:                  2020.0-166               
mkl-service:          2.3.0-py37hb782905_0     
mkl_fft:              1.0.15-py37h14836fe_0    
mkl_random:           1.1.0-py37h675688f_0     
numpy:                1.18.1-py37h93ca92e_0    
numpy-base:           1.18.1-py37hc3f5095_1    
oauthlib:             3.1.0-py_0               
openssl:              1.1.1d-he774522_4        
opt_einsum:           3.1.0-py_0               
pip:                  20.0.2-py37_1            
protobuf:             3.11.4-py37h33f27b4_0    
pyasn1:               0.4.8-py_0               
pyasn1-modules:       0.2.7-py_0               
pycparser:            2.19-py_0                
pyjwt:                1.7.1-py37_0             
pyopenssl:            19.1.0-py37_0            
pyreadline:           2.1-py37_1               
pysocks:              1.7.1-py37_0             
python:               3.7.0-hea74fb7_0         
requests:             2.22.0-py37_1            
requests-oauthlib:    1.3.0-py_0               
rsa:                  4.0-py_0                 
scipy:                1.4.1-py37h9439919_0     
setuptools:           45.2.0-py37_0            
six:                  1.14.0-py37_0            
tensorboard:          2.1.0-py3_0              
tensorflow:           2.1.0-gpu_py37h7db9008_0 
tensorflow-base:      2.1.0-gpu_py37h55f5790_0 
tensorflow-estimator: 2.1.0-pyhd54b08b_0       
termcolor:            1.1.0-py37_1             
urllib3:              1.25.8-py37_0            
vc:                   14.1-h0510ff6_4          
vs2015_runtime:       14.16.27012-hf0eaf9b_1   
werkzeug:             0.16.1-py_0              
wheel:                0.34.2-py37_0            
win_inet_pton:        1.1.0-py37_0             
wincertstore:         0.2-py37_0               
wrapt:                1.11.2-py37he774522_0    
zlib:                 1.2.11-h62dcd97_3        
```

```
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
2020-02-21 14:13:40.676403: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
```
