### ISSUE TITLE
服务器404问题

### ISSUE THREAD

**Issue by GoingTime** [tuna/issues#718]
近几日，通过conda访问服务器时异常不稳定，经常出现下载失败或404错误，通过浏览器访问正常，已经排除代理软件和hosts文件等问题。访问default通道倒是很快。

网络环境：山东青岛电信

错误代码：
(base) C:\Users\Timei>conda update conda
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 251, in _load
        raise UnavailableInvalidChannel(self.url_w_repodata_fn, 404)
    conda.exceptions.UnavailableInvalidChannel: The channel is not accessible or is invalid.
      channel name: pkgs/main
      channel url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
      error code: 404

    You will need to adjust your conda configuration to proceed.
    Use `conda config --show channels` to view your configuration's current state,
    and use `conda config --show-sources` to view config file locations.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 248, in _load
        repodata_fn=self.repodata_fn)
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 598, in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.subdir_data.Response304ContentUnchanged

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 415, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 1011, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 228, in get_reduced_index
        repodata_fn=repodata_fn)
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 105, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "D:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 598, in result_iterator
        yield fs.pop().result()
      File "D:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 435, in result
        return self.__get_result()
      File "D:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
        raise self._exception
      File "D:\ProgramData\Anaconda3\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 98, in <lambda>
        package_ref_or_match_spec))
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 110, in query
        self.load()
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 174, in load
        _internal_state = self._load()
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 255, in _load
        return self._load()
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 263, in _load
        mod_etag_headers.get('_mod'))
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 311, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 349, in _process_raw_repodata_str
        json_obj = json.loads(raw_repodata_str or '{}')
      File "D:\ProgramData\Anaconda3\lib\json\__init__.py", line 348, in loads
        return _default_decoder.decode(s)
      File "D:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "D:\ProgramData\Anaconda3\lib\json\decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Expecting ',' delimiter: line 201913 column 19 (char 5816139)

`$ D:\ProgramData\Anaconda3\Scripts\conda-script.py update conda`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=D:\ProgramData\Anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="D:\ProgramData\Anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=D:\ProgramData\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=D:\ProgramData\Anaconda3\python.exe
               CONDA_ROOT=D:\ProgramData\Anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
                 HOMEPATH=\Users\Timei
MYSQLCONNECTOR_ASSEMBLIESPATH=C:\Program Files (x86)\MySQL\Connector NET 8.0\Assemblies\v4.5.2
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=略
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=D:\Program Files\Oracle\VirtualBox\

     active environment : base
    active env location : D:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\Timei\.condarc
 populated config files : C:\Users\Timei\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.2
       base environment : D:\ProgramData\Anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : D:\ProgramData\Anaconda3\pkgs
                          C:\Users\Timei\.conda\pkgs
                          C:\Users\Timei\AppData\Local\conda\conda\pkgs
       envs directories : D:\ProgramData\Anaconda3\envs
                          C:\Users\Timei\.conda\envs
                          C:\Users\Timei\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

Upload successful.

配置文件内容：
channels:
  - defaults
channel_alias: https://mirrors.tuna.tsinghua.edu.cn/anaconda
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
ssl_verify: true
show_channel_urls: true
report_errors: true

**Comment by z4yx** [comment]
问题是持续存在的吗，比如现在还有吗

**Comment by GoingTime** [comment]
基本确定是conda4.8.2在anaconda2019.10中存在多个严重的缺陷。目前正在conda方面提交issue
