### ISSUE TITLE
建议删除 chromiumos

### ISSUE THREAD

**Issue by jiegec** [tuna/issues#838]
按照 #725 ，我建议删除镜像 chromiumos: 访问量极低，并且同步经常失败

附上删除的流程：

1. 选择候选的 repo ：最近三个月访问量小于一个阈值
2. 在本仓库新建一个相应的 issues，开始投票。
3. 指定的 TUNA 成员拥有一票否决权，通过关闭 issue 行使；其他成员享有正常的投票权，通过 Reaction 来投票
4. 一段固定的时间后，统计投票结果，如果同意删除镜像占总投票人数过半，则删除该镜像

#148

**Comment by z4yx** [comment]
作为TUNA中可能唯一的chrome os主力用户，我表示没有意见。因为这玩意儿即使有源码也太难编译了...

**Comment by scateu** [comment]
我前几天还想尝试编chromium os... >_<


-- 
Wang Kang

**Comment by scateu** [comment]
在想是不是应该在被remove之前赶紧编一次试试，也不枉那么多磁场被白白的排列，以及那么多光千里迢迢地从美国西海岸越过冰冷的海水来到了神秘的东方  [啊别理我]

**Comment by scateu** [comment]
compile big fail (sorry la.. no chinese IME)
```
[scateu@ryzen ~/chromium]$ repo sync
fatal: 无法找到远程引用 refs/heads/master
aosp/platform/frameworks/ml:
fatal: 无法找到远程引用 refs/heads/master

fatal: 无法找到远程引用 refs/heads/fwupd-1.4.1
chromiumos/third_party/fwupd:
fatal: 无法找到远程引用 refs/heads/fwupd-1.4.1

fatal: 无法找到远程引用 refs/heads/cups-2-2-8
chromiumos/third_party/cups:
fatal: 无法找到远程引用 refs/heads/cups-2-2-8

error: Cannot fetch infra/luci/client-py (GitError: infra/luci/client-py update-ref: fatal: 34b20305c7a69eb89e1abd5e2a94708db999f0a9^0: not a valid SHA1
)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run 
    self._target(*self._args, **self._kwargs)
  File "/home/scateu/chromium/.repo/repo/subcmds/sync.py", line 305, in _FetchProjectList
    success = self._FetchHelper(opt, project, *args, **kwargs)
  File "/home/scateu/chromium/.repo/repo/subcmds/sync.py", line 341, in _FetchHelper
    success = project.Sync_NetworkHalf(
  File "/home/scateu/chromium/.repo/repo/project.py", line 1560, in Sync_NetworkHalf
    self._InitMRef()
  File "/home/scateu/chromium/.repo/repo/project.py", line 2944, in _InitMRef
    self._InitAnyMRef(base + self.manifest.branch, active_git)
  File "/home/scateu/chromium/.repo/repo/project.py", line 2956, in _InitAnyMRef
    active_git.UpdateRef(ref, dst, message=msg, detach=True)
  File "/home/scateu/chromium/.repo/repo/project.py", line 3345, in UpdateRef
    self.update_ref(*cmdv)
  File "/home/scateu/chromium/.repo/repo/project.py", line 3410, in runner
    raise GitError('%s %s: %s' %
error.GitError: infra/luci/client-py update-ref: fatal: 34b20305c7a69eb89e1abd5e2a94708db999f0a9^0: not a valid SHA1

fatal: 无法找到远程引用 refs/heads/merge/continuous/chromeos-kernelupstream-5.7-rc5
chromiumos/third_party/kernel:
fatal: 无法找到远程引用 refs/heads/merge/continuous/chromeos-kernelupstream-5.7-rc5

Fetching projects:   2% (5/215) chromiumos/platform/tast-tests^Caborted by user
```

**Comment by z4yx** [comment]
已关闭同步，数据保留一段时间。

**Comment by gongwenpd** [comment]
> 
> 
> 已关闭同步，数据保留一段时间。



> 
> 
> 作为TUNA中可能唯一的chrome os主力用户，我表示没有意见。因为这玩意儿即使有源码也太难编译了...

**Comment by gongwenpd** [comment]
> 
> 
> 作为TUNA中可能唯一的chrome os主力用户，我表示没有意见。因为这玩意儿即使有源码也太难编译了...

我都编译成功了啊

**Comment by gongwenpd** [comment]
> 
> 
> 已关闭同步，数据保留一段时间。

不应该关闭。
我找遍了中国的其他镜像，都没有chromiumos， 只有清华有。
难道清华连硬盘都买不起了？

**Comment by iBug** [comment]
@gongwenpd 是的，现在 18 TB 的 UltraStar HC550 已经接近 1 万元一块了，确实搁谁都买不起了

~~利益无关：非 TUNA 成员或清华大学学生或校友~~

**Comment by skyzh** [comment]
> @gongwenpd 是的，现在 18 TB 的 UltraStar HC550 已经接近 1 万元一块了，确实搁谁都买不起了
> 
> ~利益无关：非 TUNA 成员或清华大学学生或校友~

别骂了别骂了

<del>利益无关：非 TUNA 成员或清华大学学生或校友</del>

**Comment by jiegec** [comment]
您好：
	镜像站的硬盘空间取决于一台服务器所可以承载的最大硬盘个数乘以单个硬盘的容量，而两者都已经达到极限，无法再扩容。另一方面，硬盘空间应该留给那些有更多人需要的软件，而不是满足一部分少数人的需求，还希望您可以理解。

**Comment by Harry-Chen** [comment]
> > 
> > 
> > 已关闭同步，数据保留一段时间。
> 
> 不应该关闭。
> 我找遍了中国的其他镜像，都没有chromiumos， 只有清华有。
> 难道清华连硬盘都买不起了？
> 

硬盘是有限的，软件是无限的。请注意您的措辞，否则我们将移除您的评论。
