### ISSUE TITLE
[tuna]404 at /jenkins/war/2.222.4/jenkins.war

### ISSUE THREAD

**Issue by bigbeef** [tuna/issues#862]
#### 发生了什么（What happened）
```
java.io.FileNotFoundException: https://mirrors.tuna.tsinghua.edu.cn/jenkins/war/2.222.4/jenkins.war
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3061)
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
	at java.net.URLConnection.getContentLength(URLConnection.java:485)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:412)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1227)
```
#### 期望的现象（What you expected to happen）
无法下载最新war包
#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by phy25** [comment]
请问您是如何设置镜像、下载的？

LTS 版本请使用 https://mirrors.tuna.tsinghua.edu.cn/jenkins/war-stable/

**Comment by z4yx** [comment]
楼上说得对。 https://mirrors.tuna.tsinghua.edu.cn/jenkins/war-stable/2.222.4/jenkins.war
